### ISSUE TITLE
Migrate: Import from More Fields / Types / Taxonomies

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1013]
## Task List
- [ ] More Fields: Where data is stored
- [ ] More Fields: How to map field types to Pods field types
- [ ] More Fields: How to map field type options to Pods field type options
- [ ] More Types: Where data is stored
- [ ] More Types: How to map post type options
- [ ] More Taxonomies: Where data is stored
- [ ] More Taxonomies: How to map taxonomy options
