### ISSUE TITLE
Karma Discounts add-on for Easy Digital Downloads

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1099]
[edit] This has moved over to be something I'm personally building outside of the Pods site.

Goal: Offer discounts for those who contribute back to WordPress and/or a GitHub project.

For this, we'll need to add some logic code to EDD. This is here to keep track of that and help me through the dev of it.

https://github.com/sc0ttkclark/edd-karma-discounts
## Tasks
- [x] GitHub API calls
- [x] WP Core Trac calls
- [x] Add Automatic Discount to product(s) in cart
- [x] Add fields to checkout (GitHub Username and/or WP.org Username)
- [x] Add fields to admin (Enable GitHub and/or WP karma, Discount %/$, Period [monthly, yearly, lifetime], Required contribution counts for GitHub / WP, Enable GitHub collaborators bypass [collaborators bypass contribution count requirement], Valid Product[s])
- [ ] GitHub Auth for verifying username ownership
- [ ] WordPress.org Auth for verifying username ownership

cc @pippinsplugins
## GitHub API calls

Get list of collaborators:

`https://api.github.com/repos/OWNER/REPO/collaborators`
- Loop through array of objects
- Compare $object->login to GITHUB_USERNAME

Get list of contributors:

`https://api.github.com/repos/OWNER/REPO/contributors`
- Loop through array of objects
- Compare $object->login to GITHUB_USERNAME
- Check $object->contributions against contributions count requirement
- If passes contribution requirement, check period requirement

Get list of commits from contributor since period limit from current date:

`https://api.github.com/repos/OWNER/REPO/commits?author=GITHUB_USERNAME&since=PERIOD_DATET00:00:00Z`
- Count array of objects, check against contributions count requirement
## WP Core Trac calls

Scrape (no API that I know of) Trac search at (ordered by newest to oldest):

`https://core.trac.wordpress.org/search?q=props+WPORG_USERNAME&noquickjump=1&changeset=on`
- Look for `<dl id="results">` and get contents
- Loop through `<span class="date">` contents and convert to unixtime
- Count matching dates that are `>=` than PERIOD_DATE
- If older date is matched, break loop
- Check counter against contributions count requirement
## EDD Custom Checkout Fields

https://easydigitaldownloads.com/docs/custom-checkout-fields/
## EDD Admin Fields

http://pippinsplugins.com/create-custom-payment-gateway-for-easy-digital-downloads/
