### ISSUE TITLE
Relationships - Delete Rules

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#1172]
I've been working with Xcode lately on an iPad app project. While in the Data Model manager, I noticed something with how Xcode handles relationships and the deletion of their parent entity.

So let's say you have a Book with Chapters, and let's say you've created two content types - one for each respectively.

What Xcode data modeling allows for is a special 'delete rule' on the Author > Book > Chapter relationships. Here's a few scenarios:
- **Deny:** Delete an Author, but don't let me delete it if it has books
- **Cascade:** Delete an Author, and delete it's related books; If the books have related chapters and that relationship is marked as cascade, delete related chapters; Continue cascading
- **No Action:** Delete an Author, and do nothing

It has another option called 'Nullify' but it's functionally the same as no action in the Pods world.

Additionally, since we'll be using a UI in many operations, we should be able to add another scenario for:
- **Reassign:** Delete an Author, reassign the related books to another author

You're probably most familiar with how this works as it's the same UI when deleting a User. It takes you to an interim screen to choose what to do with their posts: Reassign / Delete All Posts.
## Task List
- [ ] **Cascade:** Pre-deletion of parent item, attempt to delete related items, then delete parent item
- [ ] **Cascade Recurse:** Check related item's relationship delete rules and follow them, then delete related item
- [ ] **Deny:** Pre-deletion of parent item, check if relationship delete rules match a 'deny' and stop/warn deletion; Otherwise, delete parent item
- [ ] **Cascade Recurse on Deny:** If related item's relationship delete rules match a 'deny', block deletion of parent item; Otherwise, delete parent item
## Later
- [ ] **Add Delete Rules to Relationships options:** No Action (default), Cascade, Deny, Reassign
- [ ] **Reassign:** Pre-deletion of parent item when using UI for deleting, provide interim screen with drop-down to reassign the relationship to another parent item, to delete all related items, or to leave alone (orphan the related items)
- [ ] **Reassign via API:** Allow parameter to be sent for relationship reassignment (relationship_field > new id), if no parameter present, delete relationships but not related items (backwards compatibility)

**Comment by JoryHogeveen** [comment]
Maybe not fully related but it would be nice to also add the option in the new DFV fields to permanently remove the relationship (not just remove the relation but the actual related object).

**Comment by jimtrue** [comment]
There'd have to be options for delete inhibit, orphan protection, etc. Which are rules for typical related child records. Also if the item was related to another parent record, it couldn't be deleted.

**Comment by sc0ttkclark** [comment]
That should be covered under the tasklist in the main description but it wouldn't happen immediately -- it would happen on save (upon committing the change).

Unless you're talking about something else?

**Comment by lesliecdubs** [comment]
+1 - would use Pods on more projects if these features were available

**Comment by jimtrue** [comment]
@lesliecdubs you actually need to use the + reaction emoticon to vote up for this particular feature. GitHub has no way of tracking +1 in the comments. Only actual 'votes' show up.

Also, if you don't mind my asking: What other plugin are you using that provides relationships with delete inhibit, etc. rules at present inside WordPress?

**Comment by jimtrue** [comment]
@lesliecdubs it's a hard one to 'enforce' because not everything actually uses a delete inhibit rule (ie Inventory can be 'orphaned' but invoices typically can't be childless). Those are typically defined in Relational Databases when the tables and connections are created. At present, we don't delete the records, we just allow them to be removed from the relationship, so it works fairly well. You can also, as a workaround, write your own business rules into the post save routines to make sure things are properly protected using [`pods_api_post_save_pod_item_{podname}`](https://pods.io/docs/code/action-reference/pods_api_post_save_pod_item_podname/)

**Comment by lesliecdubs** [comment]
@jimtrue Yes, understood. Many of our relationship fields are required, so if the original content is later deleted then it leaves the required relationship field empty, leading to our issues.

Thanks for the workaround idea, we'll definitely check out that approach!

**Comment by sc0ttkclark** [comment]
Some progress on this front but it will take some more time to get it fleshed out. I'll post again and provide more details to anyone who wants to test it when it's ready.
