### ISSUE TITLE
CMB2 integration for Pods 3.0

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#2517]
Lots to do, here's the list:

- [x] Register CMB2 boxes for content types covered by Pods
- [ ] Hook into validation to do things Pods needs (find ways to bring back into CMB2 if it's generally wide-reaching) #2711
- [ ] Hook into saving to do things Pods needs (find ways to bring back into CMB2 if it's generally wide-reaching)#2712
- [ ] Hook into input to do things Pods needs (find ways to bring back into CMB2 if it's generally wide-reaching) #2713
- [ ] Rewrite JS for fields to support CMB2 loop fields #2714
- [ ] Implement composer for CMB2, remove/replace current Git submodule #2710
