### ISSUE TITLE
Add support for Term Meta coming in WP 4.4

### ISSUE THREAD

**Issue by PodsBot** [pods-framework/pods#3163]
Add support for Term Meta coming in WP 4.4 / 4.5 submitted via Slack by sc0ttkclark

- [x] Enable meta storage for Terms in PodsAPI.php
- [x] Add metadata hooks for term meta, mirroring post metadata hooks
- [x] Add metadata calls for term meta in PodsAPI::save_pod_item, mirroring post metadata calls
- [x] Find all 'taxonomy' references in Pods and adjust things as needed, should match 'post_type' functionality
- [x] Find all 'post_type' references in Pods and adjust things as needed
- [x] Run our Unit Tests against 4.4 when it has term meta
- [x] Beta testers test the UI and functionality

**Comment by sc0ttkclark** [comment]
Anyone -- How many PRs (that you contribute) do you bet that I get Term meta added in X hours? Where X is how many hours you think I will get it done in. If you go over/under the hours it takes me to get it done, you have to contribute those PRs. I will round my time up to the nearest hour. If you guess the correct number of hours it takes me, you get a super secret special surprise. Taking bets through September. If you guess the number of hours it takes me correct, I will contribute those PRs on any (sane) features or enhancements you'd like.

**Comment by sc0ttkclark** [comment]
https://github.com/pods-framework/pods/issues/3169 needs testing once 4.4 gets term meta into trunk.
