### ISSUE TITLE
2.7 Feature Release

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3364]
##### Main Milestones
- [x] #4126 Autocomplete for List View select from existing
- [x] #4137 Modal add/edit not working for ACTs
- [x] #3309, #4020 'Add New' items for relationship fields (@sc0ttkclark, @pglewis)
- [x] #4067 Convert Avatar field to DFV (@pglewis)
- [x] #4014 Cleanup and refactor
- [x] #3695 Fully replace the old Pick field
- [x] #3334 Implement scratch rewrite of File Upload field

##### General tasks
- [ ] #4039 Add New Enable/Disable Option (done, but I don't think we have any way to differentiate ACTs from Pods' Settings Pages by name alone, which is a dangling issue)
- [ ] #4026 Don't show Taggable option for autocomplete with Simple Custom Defined List
- [ ] #4038 Container with Show Edit Links, Icons, and Links disappears on regular edit
- [x] #4134 Modal title for edits
- [x] #4019 Clean up "list view" for relationships (select from existing, dashicons, etc)
- [x] #4055 Add New Label should pull "Labels" for Related Record to identify what will actually be Adding New Items Of, ie Add New Books, Add New Users, etc.
- [x]  #4051 List View should not show 'Taggable' option (done)
- [x] #4030 Access rights for add new / edit links per object type (@sc0ttkclark)
- [x] #4017 autocomplete, drag/drop

**Comment by Ramoonus** [comment]
will the minify include script_debug variable?

**Comment by pglewis** [comment]
> will the minify include script_debug variable?

That sort of thing will be considered for sure.  I'd like to generate source maps and get a workflow around that.  Debugging with minified scripts is no fun.

**Comment by pglewis** [comment]
http://jspm.io/

**Comment by pglewis** [comment]
37f3aa6 and a2f20d1 bring rollup/babel/uglify on board

**Comment by pglewis** [comment]
Time traveler notes to future self: make sure #3327 / #3319 are handled in the new MV based fields.

**Comment by sc0ttkclark** [comment]
Add New opens modal, works great but on publish or saving draft it then shows the menu / admin bar on reloading iframe.

**Comment by sc0ttkclark** [comment]
I'm working on permissions stuff here to ensure the Add New button / modal stuff doesn't show up for user accounts who do not have access to them, and that it's optional so that Add New won't show in places unwanted.

**Comment by pglewis** [comment]
I'm purging old, long-finished task list items in the first post to keep that down to a usable length.  Milestones or the 2.7 project board should probably be the go-to for anyone looking for a full list of what's been done; the tasklist here is better limited to recent and ongoing work.

**Comment by pglewis** [comment]
This is not really an "issue" and we no longer need to track big tasks on the road to beta.  

Issues/PRs on the 2.7 milestone is the way to find the status from here on out.

**Comment by renaudham** [comment]
Hi
I have just tested this new feature and it's great.
Flexible Relationships + Add new button.

Anyway I think there is a BIG thing missing UX element in this featured, to make it really easily usable by anybody:

>Case:
I have two related entities, let say one that is Project and one that is Bug
I a Project I have a Flexible Relationship for related BUGS, multiple, set as List View Mode
then also with a Add New Button

>Then currently:

I click add new
A modal open with an empty bug form
I have a related field "project" selector (select2, combobox, as set..)

That's fine
But here, the "project" selected is EMPTY
when we are coming from a Specific Project parent record, where we did Add New to open this Bug form.

This is quite not a good UX, not to have the project selected and filled by default.

**Comment by pglewis** [comment]
@renaudham: this was an old issue around to track things that were needed while working on the prototype and while in alpha.  Copy this into a new issue when you get a moment, this feedback runs a high risk of being lost, buried in an closed issue.

**Comment by jimtrue** [comment]
@renaudham Check out #4249 I believe that's what you're referring to.

**Comment by renaudham** [comment]
That's it yes thans Jim and Pglewis
