### ISSUE TITLE
Import from Flutter

### ISSUE THREAD

**Issue by thefunkhouse** [pods-framework/pods#386]
## Task List
- [ ] Where data is stored
- [ ] How to map field types to Pods field types
- [ ] How to map field type options to Pods field type options
- [ ] How to map write panels to Pods post types
- [ ] How to map write panel options to Pods post type options
