### ISSUE TITLE
CSS tweaks, fixes, and additions for 2.7

### ISSUE THREAD

**Issue by pglewis** [pods-framework/pods#3967]
Part of 2.7: #3364
PR 1 (merged): #3968 
PR 2: #4045 

- [x] select2 (we've upgraded but not all styles are applying yet)
- [x] Pods' internal dropdowns: "Add New Pod" wizard, drop-downs for field edits.  Right edges appear to get cut off for me in Chrome.
- [x] Responsive views of the Pods admin screens (fields etc)
- [x] Our fields in the admin metaboxes do not resize gracefully when there is a very wide selectbox. (Possible wontfix since it is a HTML bug.)
- [x] Labels above fields in metaboxes on the side #2797
- [x] Fix UI issues with fields on Pods Settings pages
- [x] #3122: label for a relationship dropdown on custom settings admin page is right of the field not below it
- [x] Can we work out once and for all if we can get rid of '.hidden' classes?  (#2578, #2556)
- [x] Stop using `pods-admin.css` on custom setting pages
- [x] Wizard layout fixes (minor). Some fixes widths are now scaleable
- [x] Custom component pages
  - [x] Migrate packages (uses the Wizard)
  - [x] Role editor: edit role page

Related: https://github.com/pods-framework/pods/pull/3800

**Comment by pglewis** [comment]
Not much left here, wasn't sure about that last task list item for components.  I'm ready to kill this one, we've swept what was outstanding and CSS tweaks can be taken care of as we go on future PRs.

**Comment by pglewis** [comment]
W00t!
