### ISSUE TITLE
Component: Migrate: Import from Custom Field Template

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#519]
Yeah, that plugin is pretty messy, but some sort of guided import would be better than fairing for yourself out in that wild world.
## Task List
- [ ] Where data is stored
- [ ] How to map/parse field types to Pods field types
- [ ] How to map/parse field type options to Pods field type options
