### ISSUE TITLE
New Field Type: Address / Map

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#657]
Supports Google Maps JS / Static maps and Geocoding; Support for Bing later on

PR & Task List #3634

# Old:
<details>

## Task List
- [x] Component
- [x] Custom Field Type
- [x] Admin Options for Component
- [x] Admin Options for Fields
- [x] Input styles for Address field group and Map
- [x] Output functions for address and maps
- [ ] UI method for when listed table item list (PodsUI)
- [x] Zip Code field that allows leading zeros (international)

## Additional tasks
- [x] Fix integration of the Google Maps API
- [x] Display field options (backend and frontend)
- [ ] Make sure code is set for easy integration of possible other map types (OpenStreetMap for example)
- [ ] Loads of testing with different configurations and switching between them
- [ ] Test with Pods templates and other functions
</details>

**Comment by JoryHogeveen** [comment]
@sc0ttkclark Should this field be a separate plugin or included within Pods?
I ask this because the rep you've created is for a separate plugin.
https://github.com/pods-framework/pods-address-maps

**Comment by JoryHogeveen** [comment]
Err, since when does commenting result in an assignment removal?

**Comment by JoryHogeveen** [comment]
Got the code from @sc0ttkclark compatible and working with the 2.7 branche so time to look at the features etc!

- [ ] Fix integration of the Google Maps API
- [ ] Display field options (backend and frontend)
- [ ] Make sure code is set for easy integration of possible other map types (OpenStreetMap for example)
- [ ] Loads of testing with different configurations and switching between them

**Comment by quasel** [comment]
Status? Map Field is one of the most asked questions these days ;)

**Comment by JoryHogeveen** [comment]
Doing as much as I can. It's working but can have a lot of improvements. Plus, it's not integrated in DFV structure yet.

**Comment by quasel** [comment]
Don't worry - just came up in a bunch of conversations 👍 - any idea about a timeframe? I know Scott is a busy man! ;)

**Comment by sc0ttkclark** [comment]
Mostly testing I think?

**Comment by JoryHogeveen** [comment]
See tasklist, more than just testing ;)

**Comment by jimtrue** [comment]
@JoryHogeveen This is separate from the Address Field in #3634, correct?

**Comment by JoryHogeveen** [comment]
This is the attached issue. But the todolist is maintained in the PR.

**Comment by jimtrue** [comment]
Duh, you would think I'd notice that big Pull Request tag at the top huh? Think I got a little confused when I saw two task lists ;) Thanks for the clarification @joryhogeveen

**Comment by quasel** [comment]
- ACF Output:  The data saved and returned is an array containing the markers lat, lng, and address.
- Toolset: Stores Same data as ACF details - https://wp-types.com/documentation/customizing-sites-using-php/functions/
- MetaBox:  Stores Address separate and has a map field that takes the address_field ID as input https://docs.metabox.io/fields/map/#displaying-the-map - Array keys are latitude and longitude ... 
- CMB2 no address field

**Comment by qrahaman** [comment]
Hello,
Just following up on the Slack support discussion.  I asked whether or not this field would also auto-generate the location data; such as, city, country, and latitude and longitude.  I was told it would which is fantastic.  In my particular case, my users are effectively playing a visual measurement game on their device, mobile or desktop, and upon completion of the game, a post/pod is submitted.  The submission contains a whole host of data.  I would like their location to be part of that submission (without their having to either input that data or asked for approval to submit location data) since it will be used for filtering their scores by location and used to apply a marker to a global map.  It would be awesome if it could be integrated with FacetWP.  Is there a projected delivery date for this field type addition?

**Comment by vesna-droid** [comment]
It would be cool if there would be a display option of a map with flags for every location entered for some post type or taxonomy or user. To use as a one map showing all the locations of some event or taxonomy of events or locations of users origins.

**Comment by JoryHogeveen** [comment]
@vesna-droid 
While it's not implemented yet and only available through code.
This is my current implementation for a grouped map:
https://github.com/JoryHogeveen/pods-address-maps/blob/master/pods-maps/pods-maps.php#L67-L88

You can pass multiple values into the first parameter (array format) and it will show all of these on one single map.

**Comment by vesna-droid** [comment]
Excellent. Altough I'm a beginner in php coding and could use an example of passing actual addresses (from meta custom fields of posts or users) as array or even hire someone willing to establish this at our web place... Feel free to send me examples if you have them and willing to share for purpose of my learning...
