### ISSUE TITLE
CodePress Admin Columns integration

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#733]
- Filter for which custom fields show for each post type (to be able to remove, or add to the list, mainly for table-based Pods which we need to add our fields into)
- Filter for which post types show in the list (to be able to take our internal Pods post types out for _pods_pod, _pods_field, etc..)
- Advanced Content Type integration, to allow for Admin Columns to pick up and manage ACT default UI through pods_admin_ui_podname $ui filter -- code to be provided to Tobias @codepress -- and Tobias will implement new UI tweaks in his plugin to support more types of content other than just Post Types, which should lead to fostering further development support for the core list table classes of Taxonomies, Media, Users, and Comments
## Task List
- [x] Filter fields to show Pods table/meta fields
- [x] Filter post types to hide Pods internal types
- [ ] ~~Advanced Content Type integration to control admin columns shown in Pods UI~~

**Comment by virgiltrasca** [comment]
@sc0ttkclark integrating pod's Advanced Content Types into Admin Columns it's indeed very useful.

**Comment by Nathaniel-Fernandes** [comment]
I agree! It would be a great help :). 

As per [this forum](https://www.admincolumns.com/forums/topic/table-based-storage-of-pods-with-ac-pro-issue/) on Admin Columns Pro, the main reason they don't support Advanced Content Types is b/c there are not enough pre-made hooks.

**Comment by quasel** [comment]
Won't expect that to happen anytime soon ACT are a relict from times before WordPress had the CPT option and should only be used in a very few cases when you really are aware of the huge drawbacks but need the advantages they offer!

**Comment by JoryHogeveen** [comment]
@sc0ttkclark For 2.8 you were planning to refactor the PodsView class right? Will this fix/enhance integration?

**Comment by Nathaniel-Fernandes** [comment]
@quasel yeah I briefly looked at the WP CPT but chose ACT because of the better database design - I have thousands of items each with 25+ custom fields. That would tremendously increase the post_meta size and make it harder to sync between dev and live.

**Comment by Nathaniel-Fernandes** [comment]
> 
> 
> @sc0ttkclark For 2.8 you were planning to refactor the PodsView class right? Will this fix/enhance integration?

On this topic, could I suggest showing the image custom field as an actual image in the admin dashboard for ACT?

**Comment by quasel** [comment]
@Nathaniel-Fernandes well pods hast the option to store the CPT meta data in a table ( Table Storage - can be selected on CPT creation ) it's sort of an in-between solution to drastically reduce joins because the DB size stays the same ;) just better for search and read ^^ and with https://pods-pro.skc.dev/downloads/advanced-relationship-storage/ it's getting close ;)
