### ISSUE TITLE
Component: Gravity Forms integration

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#81]
Gravity Forms component to allow you to map submissions from GF forms to Pods

## Task List

- [x] GF submission mapping
- [x] UI to map a GF form to a Pod, field-by-field mapping with additional options (using Pods field admin UI)
- [x] Ability to use Pod data for pre-populating select/multiselect/etc fields in GF
- [x] PodsUI admin utilization of GF forms for add/edit

**Comment by poontificate** [comment]
Is this plugin able to map GF submission into a Pods relationship field? So far i've tried linking it to Pods relationship field - simple and other Pods but to no avail.

**Comment by sc0ttkclark** [comment]
Great :)
