### ISSUE TITLE
Migrate: Import from Types

### ISSUE THREAD

**Issue by markoheijnen** [pods-framework/pods#966]
From this ticket I'm trying to look into Types and how we can create an importer for Pods
## To-dos
- [ ] Lay out where data is stored for content type settings (Post Types / Taxonomies)
- [ ] Consider how best to map content type settings over to Pods (if there are matches for each, or where they differ)
- [ ] Lay out where data is stored for custom field settings
- [ ] Consider how best to map Types field types/settings over to Pods (if there are matches for each, or where they differ)
- [ ] Confirm whether or not Types stores ALL field data in wp_postmeta and if it's stored cleanly

**Comment by jimtrue** [comment]
@Jantiff See that + Smiley Face in the first description of the post and that I just did a thumbs up for it? That's how you upvote an issue that Needs Votes. This probably won't happen without 'feature funding', but votes will let us know how much it is wanted.

**Comment by Jantiff** [comment]
Thanks alot! 👍

**Comment by coercoer** [comment]
I just 👍 too, I'd appreciate this tool. Pods rules, unfortunately I found out a bit late after using Toolset Types and getting stuck time and again. Pods is so much easier to understand, better at displaying templates, and flexible to boot! I'd love to migrate my sites from Toolset to Pods. Plus 1 for this plan.

**Comment by arturbonnett** [comment]
:+1:

**Comment by dsecareanu** [comment]
Would love to have an option to migrate from ACF to Pods.

**Comment by Jantiff** [comment]
I managed to migrate (one custom type incl. fields) from Tool Types to Pods by doing the following:
first, I downloaded the contents of the custom type I wanted to migrate (for safety it may be better to backup everything from your site) directly from Wordpress tools -> download data.
I looked inside the xml file and detected the internal names of the fields of my custom type.
Find these lines 
<wp:post_type><![CDATA[mycontenttype]]></wp:post_type>
(So, my Contenttype's name would be mycontenttype)

<wp:postmeta>
		<wp:meta_key><![CDATA[wpcf-customfield1]]></wp:meta_key> 
...
That is my first customfield called customfield1 from Toolset Types. The beginning "wpcf-" is added to all custom fields of Toolset Types (at least in my version which was the last version which was free).

As I did not have many custom types and custom fields, I did not write any code to migrate them to pods. I simply deactivated Toolset Types. The data in the database remained there for all custom type pages. I then added a custom type and according custom fields in pods, using the same names (the names I found in the xml file I had downloaded).
After adding these to Pods, the content was immediately back, now useable and changeable with Pods. 
There were some functions I had programmed for the fields when using Toolset Types which I had to rewrite using the Pods syntax.
Now it all works fine. 
By the way, afterwards I changed the display names of the custom fields by removing "wpcf-".

I guess migrating from ACF to Pods could be done in a similar way as long as there is no migration tool. Just try to figure out how ACF has named your custom types and fields in the database and then deactivate ACF and add all to Pods. But be sure to make a backup before!

**Comment by Jantiff** [comment]
Hmm, some of the xml code was removed ... :(
This is what I wanted to post (oh, and I forgot to write: I searched for my contenttype name and customfield names in the xml to find these lines):
\<wp:post_type\>\<\!\[CDATA\[mycontenttype\]\]\>\<\/wp:post_type\>
and
\<wp:postmeta\>
		\<wp:meta_key\>\<\!\[CDATA\[wpcf-customfield1\]\]\>\<\/wp:meta_key\>
