### ISSUE TITLE
field() Traversal should be able to reference table/meta

### ISSUE THREAD

**Issue by sc0ttkclark** [pods-framework/pods#971]
``` php
// A field on the post type that's part of it's object table
$post_title = $pod->field( 'related_post_type.post_title' );

// A relationship field on the post type
$another_relationship = $pod->field( 'related_post_type.another_relationship' );

// A relationship (custom simple) field on the post type that's meta-based
$custom_meta_field = $pod->field( 'related_post_type.custom_simple_relationship' );

// A field on the post type that's meta-based
$custom_meta_field = $pod->field( 'related_post_type.custom_meta_field' );

// A field on the post type that's table-based
$custom_table_field = $pod->field( 'another_post_type.custom_table_field' );

// A field on the taxonomy that's part of it's object table (part of the new Taxonomy field type handling)
$term_id = $pod->field( 'taxonomy_name.term_id' );

// A field on the taxonomy that's table-based (part of the new Taxonomy field type handling)
$custom_table_field = $pod->field( 'taxonomy_name.custom_table_field' );
```

Right now, you can only reference fields on that object, or relationships/file uploads. It doesn't let you grab field values that are meta-based or on the Pods-created table.
## Available options as of Pods 2.3
- [x] **related_post_type.post_title**
- [x] **related_post_type.another_relationship**
- [x] **related_post_type.custom_simple_relationship** _(pending confirmation of unit test)_
- [x] **related_post_type.custom_meta_field**
- [x] **another_post_type.custom_table_field**
- [ ] **taxonomy_name.term_id** _(pending confirmation of unit test)_
- [ ] **taxonomy_name.custom_table_field** _(pending confirmation of unit test)_
- [x] **post_thumbnail** _(for post types)_
- [x] **post_thumbnail.full** _(for post types, traversal is the size to use, thumbnail default, accepts thumbnail, medium, large, full, 400x111, etc)_
- [x] **post_thumbnail_url** _(for post types)_
- [x] **post_thumbnail_url.full** _(for post types, traversal is the size to use, thumbnail default, accepts thumbnail, medium, large, full, 400x111, etc)_
- [x] **avatar** _(for users)_
- [x] **avatar.32** _(for users, traversal is the size to use, must be integer, default is 96, max is 512)_
- [x] **image_attachment.123** _(output an image by attachment ID)_
- [x] **image_attachment.123.full** _(output an image by attachment ID, traversal is the size to use, thumbnail default, accepts thumbnail, medium, large, full, 400x111, etc)_
- [x] **image_attachment_url.123** _(output an image URL by attachment ID)_
- [x] **image_attachment_url.123.full** _(output an image URL by attachment ID, traversal is the size to use, thumbnail default, accepts thumbnail, medium, large, full, 400x111, etc)_
- [x] **file_field_name._src** / **file_field_name._src_full** URL for full image size
- [x] **file_field_name._src_sizename** URL for custom image size
- [x] **file_field_name._src_thumbnail** URL for thumbnail image size

**Comment by borantula** [comment]
So, is there a solution for taxonomy.term_id now or is it still on hold?
